import { generateProtocolForPacient } from "protocols-generator";

jest.mock("uuid", () => {
  return {
    v4: () => { return "protocol generated by v4 mock" }
  }
});

describe("protocol tests", () => {
  it("should generate a protocol for pacient", async () => {
    const { priority, date, pacient, protocol } = generateProtocolForPacient("Carls", "Varls", true);

    expect(priority).toBe(true);
    expect(date).toBe(date);
    expect(pacient).toBe("Carls Varls");
    expect(protocol).toBe("protocol generated by v4 mock");
  });
});